Web/testpjt/articles/urls.py
from django.urls import path
from . import views

# articles/urls.py
app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('detail/<int:article_id>', views.detail, name = 'detail'),
    path('edit/<int:article_id>', views.edit, name='edit'),
    path('create/', views.create, name='create'),
    path('save/', views.save, name='save'),
    path('update/<int:article_id>', views.update, name='update'),
    path('delete/<int:article_id>', views.delete, name='delete')
]

Web/testpjt/testpjt/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views  # articles app의 views.py 파일 불러오기 
from movies import views as movie_views 

urlpatterns = [
    path('admin/', admin.site.urls),
    # articles라는 경로로 들어왔을 때
    # articles app의 views.py파일의 index함수를 호출
    path('articles/', include('articles.urls')),
    # path('movies/', views.movies),
    # path('save_review/', views.save_review)
]

Web/testpjt/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Web/testpjt/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles
    }
    return render(request, 'articles/index.html', context)

def detail(request, article_id):
    article = Article.objects.get(pk=article_id)
    context = {
        'article' : article
    }
    return render(request, 'articles/detail.html', context)

def create(request):
    return render(request, 'articles/create.html')

def save(request):
    data = request.POST
    # 방법 1) 인스턴스 생성해서 데이터 추가
    # article = Article()
    # article.title = data.get('title')
    # article.content = data.get('content')
    # article.save()

    # 방법 2) QuerySet API 이용해서 데이터 추가
    new_article = Article.objects.create(title=data.get('title'), content=data.get('content'))

    return redirect('articles:detail', article_id=new_article.pk)

def edit(request, article_id):
    article = Article.objects.get(pk=article_id)
    context = {
      'article':article
      }
    return render(request, 'articles/edit.html', context)

def update(request,article_id):
    data = request.POST
    Article.objects.filter(pk=article_id).update(
        title=data.get('title'), content = data.get('content'))
    return redirect('articles:detail', article_id=article_id)

def delete(request, article_id):
    data = request.POST
    delete_article = Article.objects.filter(pk=article_id).delete()
    return redirect('articles:index')





# def movies(request):
#     favorite_movie = '범죄도시'
#     movie_list = ['범죄도시', '극한직업', '기생충', '아바타']
#     context = {
#         'favorite_movie' : favorite_movie,
#         'movie_list' : movie_list
#     }
#     return render(request, 'articles/movies.html', context)

# def save_review(request):
#     data = request.GET
#     context = {
#         'review_text': data.get('review_text')
#     }
#     return render(request, 'articles/save_review.html', context)

Web/testpjt/movies/views.py
from django.shortcuts import render

# Create your views here.
def movies(request):
    favorite_movie = '범죄도시'
    movie_list = ['범죄도시', '극한직업', '기생충', '아바타']
    context = {
        'favorite_movie' : favorite_movie,
        'movie_list' : movie_list
    }
    return render(request, 'movies/movies.html', context)

Web/testpjt/articles/templates/articles/create.html
{% extends "articles/base.html" %}

{% block content %}
    <form action="{% url "articles:save" %}" method="POST">
        {% csrf_token %}
        <div>
            <label for="title">Title</label>
            <input type="text" name="title" id="title">
        </div><br>
        <div>
            <label for="content">Content:</label>
            <textarea name="content" id="content"></textarea>
        </div><br>
        <input type="submit">
    </form>
    <hr>
    <a href="{% url "articles:index" %}">[back]</a>


{% endblock content %}

Web/testpjt/articles/templates/articles/detail.html
{% extends "articles/base.html" %}

{% block content %}
    <h1>DETAIL</h1>
    <h2> {{article.pk}} 번째 글 </h2>
    <hr>
    <p> 제목 : {{article.title}} </p>
    <p> 내용 : {{article.content}} </p>
    <hr>
    <a href="{% url 'articles:edit' article_id=article.pk%}">[수정하기]</a>
    <hr>
    <a href="{% url 'articles:delete' article_id=article.pk %}">[삭제하기]</a>
    <hr>
    <a href="{% url 'articles:index' %}">[back]</a>

{% endblock content %}

Web/testpjt/articles/templates/articles/edit.html
{% extends "articles/base.html" %}

{% block content %}
    <h1>EDIT</h1>
    <form action="{% url "articles:update" article_id=article.pk %}" method="POST">
    {% csrf_token %}
    <div>
        <label for="title">Title : </label>
        <input type="text" name="title" id="title" value="{{ aritcle.title }}">
    </div><br>
    <div>
        <label for="content">Content : </label>
        <textarea name="content" id="content">{{ article.content }}</textarea>
    </div><br>
    <input type="submit" value="수정하기">
    </form>
    <hr>
    <a href="{% url "articles:index" %}">[back]</a>
{% endblock content %}

Web/testpjt/articles/templates/articles/index.html
{% extends "articles/base.html" %}

{% block content %}
  <h1>Articles</h1>
  <a href="{% url 'articles:create' %}">게시글 작성하기</a>
  <hr>
  {% for article in articles %}
    <p>글 번호 : {{ article.pk }} </p>
    <a href="{% url 'articles:detail' article_id=article.pk %}">
      <p>글 제목 : {{ article.title }} </p>
    </a>
    <p>글 내용 : {{ article.content }} </p>
    <hr>
  {% endfor %}
{% endblock content %}

Web/testpjt/articles/templates/articles/movies.html
    {% extends "articles/base.html" %}

    {% block content %}
        <h2> 가장 좋아하는 영화s123 {{favorite_movie}} </h2>
        <h2>천만 영화 목록 </h2>
        {% if movie_list %}
            <ul> 
                {% for movie in movie_list %}
                    <li> {{movie}} </li>
                {% endfor %}
            </ul>  
        {% endif %} 

        <form action='/save_review/' method="GET">
            <label for='review_text_id'>리뷰: </label>
            <input type='text' name='review_text' id = 'review_text_id'>
            <input type='submit' value='submit'>
        </form>
    {% endblock content %}

Web/testpjt/articles/templates/articles/save.html
{% extends "articles/base.html" %}

{% block content %}
    <h1>게시글 작성 완료</h1>
{% endblock content %}

Web/testpjt/articles/templates/articles/save_review.html
{% extends "articles/base.html" %}

{% block content %}
    <h1> {{review_text}} </h1>
{% endblock content %}

Web/testpjt/movies/templates/movies/movies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movies</title>
</head>
<body>
    <h2> 가장 좋아하는 영화 {{favorite_movie}} </h2>
    <h2>천만 영화 목록 </h2>
    {% if movie_list %}
        <ul> 
            {% for movie in movie_list %}
                <li> {{movie}} </li>
            {% endfor %}
        </ul>
    {% endif %} 
</body>
</html>